name: 🚀 Feature Request
description: Suggest new features or integrations
title: '[FEATURE] '
labels: ['feature', 'enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What new capability?
      placeholder: "Describe the Feature capability"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why this feature?
      description: User need or competitor gap?
      placeholder: ""
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: APIs, libraries, rough approach?
      placeholder: ""