// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzgtzn7PIQQhVxxWVS8pbqvf8ckIx6Nu8',
    appId: '1:345065440152:web:3a7076304f59272bf021ed',
    messagingSenderId: '345065440152',
    projectId: 'campus-runner-51ee3',
    authDomain: 'campus-runner-51ee3.firebaseapp.com',
    storageBucket: 'campus-runner-51ee3.firebasestorage.app',
    measurementId: 'G-T6RSTJTD2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr-86Ctixkb4mw-mnSTax1oBvLw0musFI',
    appId: '1:345065440152:android:0287da5023adf7a9f021ed',
    messagingSenderId: '345065440152',
    projectId: 'campus-runner-51ee3',
    storageBucket: 'campus-runner-51ee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-bxP5igbYNFAX0nX_Xy3PTUartfhb5YE',
    appId: '1:345065440152:ios:ec8312e64a209b0bf021ed',
    messagingSenderId: '345065440152',
    projectId: 'campus-runner-51ee3',
    storageBucket: 'campus-runner-51ee3.firebasestorage.app',
    iosBundleId: 'com.example.campusRunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-bxP5igbYNFAX0nX_Xy3PTUartfhb5YE',
    appId: '1:345065440152:ios:ec8312e64a209b0bf021ed',
    messagingSenderId: '345065440152',
    projectId: 'campus-runner-51ee3',
    storageBucket: 'campus-runner-51ee3.firebasestorage.app',
    iosBundleId: 'com.example.campusRunner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzgtzn7PIQQhVxxWVS8pbqvf8ckIx6Nu8',
    appId: '1:345065440152:web:43b3c51313f0045cf021ed',
    messagingSenderId: '345065440152',
    projectId: 'campus-runner-51ee3',
    authDomain: 'campus-runner-51ee3.firebaseapp.com',
    storageBucket: 'campus-runner-51ee3.firebasestorage.app',
    measurementId: 'G-LJQVHY2QYH',
  );
}
